### ISSUE TITLE
Change tests parallelizing mechanism

### ISSUE THREAD

**Issue by IlyaFaer** [googleapis/python-spanner-django#471]
While working on the last PR I've got in the situation when kokoro checks passed (green), but after some time their status became red (because some parallelized tests failed - some can take [more than 20 min.](https://source.cloud.google.com/results/invocations/0417017c-7716-4076-87b7-d2a5dd5a1d48/targets)). This can cause problems with "automerge" (bot that runs checks and merges PR automatically, if they are green). Automerge [is used](https://github.com/googleapis/python-spanner/pull/133) in the original Spanner repo, which means this API will be using it too. And, after all, it's inconvenient when checks are green, but can become red in future (~35 min.).

**Comment by mf2199** [comment]
From a `kokoro` [presubmit log](https://source.cloud.google.com/results/invocations/6c03f772-a530-49e3-b7ec-de53b42901b0/targets/cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fpython-spanner-django%2Fpresubmit%2Fworker_4/log):

```
...

startIndex: 96 endIndex: 120 totalApps 24
createInstance: throttling by sleeping for 11.098s
Sleeping for 632.969759ms
panic: rpc error: code = ResourceExhausted desc = Project 1065521786570 cannot add 1 nodes in region us-west1.

goroutine 1 [running]:
main.main()
	/Users/emmanuelodeke/Desktop/django-spanner/parallelize_tests.go:81 +0xfa1


[ID: 3692114] Build finished after 150 secs, exit value: 2


Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
[17:14:00] Collecting build artifacts from build VM
Build script failed with exit code: 2
```

The way parallelization implemented here is not present among other APIs (Spanner, Bigtable, Storage etc.). Hence I'd suggest removing it at least for now.

**Comment by c24t** [comment]
I'm seeing the same error in https://github.com/googleapis/python-spanner-django/pull/469, which shouldn't have any real test failures. It looks like some test runs may not be cleaning up test instances, which prevents us from creating new instances.

**Comment by c24t** [comment]
> 	/Users/emmanuelodeke/Desktop/django-spanner/parallelize_tests.go:81 +0xfa1

@odeke-em what's ups with this path? Was this the source for `bin/parallelize_tests_linux`? In any case we probably want to avoid checking on opaque binaries, even if they're only used in CI.

**Comment by c24t** [comment]
There may also be some answers in https://github.com/googleapis/python-spanner-django/issues/413 and https://github.com/googleapis/python-spanner-django/commit/43993b1577a53314ee995d2ef68fce429ca8d33d. It looks like create instance calls are randomly staggered across workers (https://github.com/googleapis/python-spanner-django/commit/43993b1577a53314ee995d2ef68fce429ca8d33d#diff-b65ed1fb7a1fb00036a946fa744fb712R74), presumably because this fails if we call it too frequently? In which case we may have just gotten unlucky with timing. In any case throttling the tests like this is sure to cause some flakiness, and we should probably find a better way to avoid resource limits.

In any case it sounds like we have three problems here: (1) kokoro reports that tests pass (instead of just pending) before reporting that they fail, (2) the kokoro tests are flaky or outright broken, and (3) other spanner repos don't run tests this way.

(1) and (2) seem like a high priority, but (3) may not be a problem for a while. If `parallelize_tests` is causing (1) or (2) instead of kokoro config issues or the tests just being flaky, then that's good reason to remove it. But I'd like to know why this is causing problems (and tests are failing) now but not in the past.

**Comment by IlyaFaer** [comment]
> (2) the kokoro tests are flaky or outright broken

Looking at the Go code: it creates an instance and plans deleting it on the test end with `defer`:
https://github.com/googleapis/python-spanner-django/blob/5551b58d7983edc57f0482000254ea2df21476d6/parallelize_tests.go#L83

But if the instance deletion or the test itself fails, the instance will stay in project. For such a cases we usually use pre-test cleanup: list all the instances within project and delete those older then 24h ([example in Go](https://github.com/googleapis/google-cloud-go/blob/363003cbe8d2614211d5cc0d7c9f00106609c8ee/spanner/integration_test.go#L2858-L2891)) - that is done before starting the test. We use such a practise in Spanner, Storage, PubSub, etc., and I don't see anything like this here.

> (1) kokoro reports that tests pass (instead of just pending) before reporting that they fail

Looks like the longest test worker can take ~2 hours to finish (see [logs](https://source.cloud.google.com/results/invocations/ea1ce947-860c-42c2-b065-7c96988c8ffb/targets)). It's the longest one, meaning if half of the workers are longer then 0.5h then it can take several hours to run all the tests if we'll unparallelize them. This will hit the build limit of 2h.

All of it means that we should change the tests parallelizing method to fix the mentioned problems and not to hit any limit. Seems to me the best way is to split workers onto several kokoro checks (see [the example](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/4532)).

**Comment by vi3k6i5** [comment]
Ideally kokoro should not report success until all it's child workers have finished executing. I will look into how to change the kokoro return to wait until all workers are either successful or failed.

**Comment by vi3k6i5** [comment]
Resolved by making kokoro return status after all tests are finished.
